### ISSUE TITLE
Update "about" information

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/modelviewer-mf6#5]
Since we are going to start producing beta versions, it might be good to update the "about" window to reflect the build date so we can differentiate the evolving versions.  The screen shot below is from the version downloaded yesterday.

![image](https://user-images.githubusercontent.com/3372403/149342934-59855394-d8c0-4f86-88f9-da61020ce8d9.png)

**Comment by scharlton2** [comment]
I'll automate this later, for now I'll update it manually.

**Comment by scharlton2** [comment]
Change about from

![image](https://user-images.githubusercontent.com/7538707/151429562-0a9792c5-f099-4cc6-a9f8-9a665728d615.png)

to

![image](https://user-images.githubusercontent.com/7538707/151432575-71f66b36-3aa1-4977-8c25-3fe2d7d8fc2e.png)
