### ISSUE TITLE
Selecting Name file doesn't work with this model.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modelviewer-mf6#7]
[PSMP_Pathlines.zip](https://github.com/MODFLOW-USGS/modelviewer-mf6/files/7921455/PSMP_Pathlines.zip)
The attached model can not read the model if you select the name file for the flow model. It can be viewed if you select the grid, head, and name file individually. The head file has the extension .bhd.

**Comment by scharlton2** [comment]
Hi @rbwinst-usgs,

Sorry, I'm not that familiar running modflow/ModelMuse.  I'm trying to run the example you supplied in [PSMP_Pathlines.zip](https://github.com/MODFLOW-USGS/modelviewer-mf6/files/7921455/PSMP_Pathlines.zip) using MODFLOW-2005/Modpath-6.0.

Here's what I tried:

 Opened PSMP_Pathlines.gpt and changed the 'Model Selection' to 'MODFLOW-2005'
 Clicked 'Model->Edit Geo Reference' and set the Start date to 1/24/2022.
 Saved it and ran it from ModelMuse.  I got a red unhappy face from ModelMonitor.
I closed ModelMonitor and this was the output:

```
D:\Issues\modflow\issue-7\modflow-2005>call D:\Issues\modflow\issue-7\ModelMuse4_3\bin\ModelMonitor.exe -m C:\WRDAPP\MF2005.1_12\bin\mf2005.exe -n D:\Issues\modflow\issue-7\modflow-2005\PSMP_Pathlines.nam

D:\Issues\modflow\issue-7\modflow-2005>Start Notepad.exe D:\Issues\modflow\issue-7\modflow-2005\PSMP_Pathlines.lst

D:\Issues\modflow\issue-7\modflow-2005>call RunModpath.bat

D:\Issues\modflow\issue-7\modflow-2005>call mp.bat /wait

D:\Issues\modflow\issue-7\modflow-2005>C:\WRDAPP\modpath.6_0\bin\mp6.exe PSMP_Pathlines.mpsim
Processing basic data ...
Checking head file ...
Checking budget file and building index ...
Unable to determine the precision of the budget file

D:\Issues\modflow\issue-7\modflow-2005>pause
Press any key to continue . . .
```

and here's the 'Errors and Warnings' output:

````
Warnings
  MODFLOW
    Missing Geo Reference data
      The projection of your model is undefined. You can define it in "Model|Edit Geo Ref."
````

I'm not sure what to set the projection to (is it required?) and I don't think I'm getting any pathline files (*.lin;*.path;*.pathline).

Thanks,
Scott

**Comment by rbwinst-usgs** [comment]
This was a MODFLOW-6 model along with MODPATH 7. All the model input and output was already included. You shouldn't have needed to run the model again. I don't think the projection should be needed for Model Viewer. It certainly isn't needed by MODFLOW or MODPATH. You do need a projection when creating a model archive but that isn't something that Model Viewer needs to deal with.

**Comment by scharlton2** [comment]
Hi @rbwinst-usgs,

I wanted to open this run in the previous version of Model Viewer 1.6 so that I could see how it used to work.  When I ran it using ModelMuse/MODFLOW-2005/ModPath-6.0 no pathline files were generated.

Thanks,
Scott

**Comment by rbwinst-usgs** [comment]
[PSMP_Pathlines_2005.zip](https://github.com/MODFLOW-USGS/modelviewer-mf6/files/7928496/PSMP_Pathlines_2005.zip)
Here is a 2005 version of the model. You have to select a flow package and a solver package when converting from MODFLOW 6 to MODFLOW-2005.
